### ISSUE TITLE
Cleaning an array of folders will wipe out the root folder

### ISSUE THREAD

**Issue by jeff-harnois** [reputationdefender/grunt-clean#2]
When passing an array of folders:

```
clean: {
  folder: ["assets/js/","assets/tpl/"]
},
```

node throws:

```
node.js:460
    var cwd = process.cwd();
                  ^
Error: ENOENT, no such file or directory
    at Function.resolveArgv0 (node.js:460:23)
    at startup (node.js:51:13)
    at node.js:551:3
```

and then continues the process.  Since it is not changing the working directory before it continues, it removes all files from the current working directory.

**Comment by mutewinter** [comment]
Yep, ran into this issue today and nearly lost two hours of code.
