### ISSUE TITLE
Can't delete files in a folder without deleting the folder

### ISSUE THREAD

**Issue by manuelbieh** [reputationdefender/grunt-clean#5]
I'm trying to delete files within a folder without deleting the folder itself but either the complete folder is deleted or the files are not. I tried the following:
1. `clean: {
   folder: "dist/htdocs/uploads/userfiles/**/*"
   }`
   (Nothing is deleted, neither files nor folder)
2. `clean: {
   folder: "dist/htdocs/uploads/userfiles/*"
   }`
   (Same as 1.)
3. `clean: {
   folder: "dist/htdocs/uploads/userfiles"
   }`
   (Files are deleted but folder as well (unwanted))

(Using Windows 7)

**Comment by jeff-harnois** [comment]
The intent of this task is to remove folders at once, not remove individual files.  Usually this task is run at the start of a grunt task chain, and is followed up by whatever concatenation tasks and other file generation tasks you would normally run.
